Repository nordcloud/GNUI, pull requests merged in 2020-09, with the labels that each got.

#157 [CO-189] Menu item hover fix
  .gitignore
  src/components/navigation/Navigation.tsx
Labels: bug

#159 [CO-190] cell border
  package.json
  src/components/table/Table.tsx
  src/stories/Table.stories.mdx
Labels: documentation, style

#158 [CO-201] Improve and refactor input components
  .github/workflows/ release.yaml
  .huskyrc
  package-lock.json
  package.json
  src/components/container/Container.tsx
  src/components/dropdown/Dropdown.tsx
  src/components/form/Form.tsx
  src/components/input/Input.tsx
  src/components/input/InputUpload.tsx
  src/components/input/index.tsx
Labels: bug, enhancement

#168 [Improvement] Sidebar footer
  package.json
  src/components/modal/Modal.tsx
  src/components/modal/types.ts
  src/components/sidebar/Sidebar.tsx
  src/components/sidebar/types.ts
  src/stories/Modal.stories.mdx
  src/stories/Sidebar.stories.mdx
  src/stories/Switch.stories.mdx
  src/theme/index.tsx
Labels: enhancement
