Repository nordcloud/GNUI, pull requests merged in 2021-02, with the labels that each got.

#262 Add native attribute props to the button element
  src/components/button/Button.tsx
Labels: bug

#269 refactor theme, add & fix types
  src/components/box/Box.tsx
  src/components/button/Button.tsx
  src/components/heading/Heading.tsx
  src/components/input/Input.tsx
  src/components/multiselect/Multiselect.tsx
  src/components/selectbutton/SelectButton.tsx
  src/components/sidebar/Sidebar.tsx
  src/components/tag/Tag.tsx
  src/components/text/Text.tsx
  src/components/toggle/Toggle.tsx
  src/theme/config.ts
  src/theme/index.tsx
  src/utils/setcolor.tsx
Labels: bug, enhancement

#267 Add accessibility for inputs & labels
  src/components/form/Form.stories.mdx
  src/components/form/Form.tsx
  src/components/input/Description.tsx
  src/components/input/Input.stories.mdx
  src/components/input/Input.tsx
  src/components/input/InputSearch.tsx
  src/components/input/InputUpload.tsx
  src/components/input/Label.tsx
  src/components/input/index.tsx
  src/components/input/styles.tsx
  src/components/input/types.ts
Labels: bug

#268 Improve types
  src/components/message/Message.stories.mdx
  src/components/message/Message.tsx
  src/components/selectbutton/SelectButton.stories.mdx
  src/components/selectbutton/SelectButton.tsx
  src/components/svgicon/SVGIcon.tsx
  src/components/tabs/Tabs.tsx
  src/components/text/Text.tsx
  src/components/toggle/Toggle.stories.mdx
  src/components/toggle/Toggle.tsx
Labels: enhancement

#272 Fix font weight
  src/components/sidebar/Sidebar.tsx
  src/components/sidebar/styles.tsx
Labels: bug

#273 Add const assertions for theme config
  src/theme/config.ts
Labels: enhancement

#276 Add textarea
  package.json
  src/components/input/styles.tsx
  src/components/textarea/Textarea.stories.mdx
  src/components/textarea/Textarea.tsx
  src/components/textarea/index.tsx
Labels: enhancement

#274 Force node/npm versions
  .npmrc
  .nvmrc
  amplify.yml
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement
