Repository nordcloud/GNUI, pull requests merged in 2021-04, with the labels that each got.

#288 [Documentation] Update button and box component documentation
  package-lock.json
  package.json
  src/components/box/Box.stories.mdx
  src/components/button/Button.stories.mdx
  src/components/tooltip/Tooltip.tsx
Labels: documentation

#293 [Docs] Add docs for dropdown
  src/components/dropdown/Dropdown.stories.mdx
Labels: documentation

#292 [Docs] Add checkbox docs
  src/components/checkbox/Checkbox.stories.mdx
Labels: documentation

#290 [Docs] Add barchart and breadcrumbs documentation
  src/components/barchart/BarChart.stories.mdx
  src/components/breadcrumbs/Breadcrumbs.stories.mdx
Labels: documentation

#289 [Docs] Add accordion documentation
  src/components/accordion/Accordion.stories.mdx
Labels: documentation

#295 [Docs] Add docs for Text component
  src/components/text/Text.stories.mdx
Labels: documentation

#302 [Docs] Add docs for pagination and spacer
  src/components/pagination/Pagination.stories.mdx
  src/components/spacer/Spacer.stories.mdx
Labels: documentation

#300 [Docs] Add documentation for Toast
  src/components/toast/Toast.stories.mdx
  src/components/toast/Toast.tsx
Labels: documentation

#298 [Docs] Add docs for message component
  src/components/message/Message.stories.mdx
Labels: documentation

#297 [Docs] Add docs for loader
  src/components/loader/Loader.stories.mdx
Labels: documentation

#294 [Docs] Add docs for heading
  src/components/checkbox/Checkbox.stories.mdx
  src/components/dropdown/Dropdown.stories.mdx
  src/components/heading/Headings.stories.mdx
Labels: documentation

#296 [Docs] Add docs for list component
  src/components/list/List.stories.mdx
Labels: documentation

#299 [Docs] Add docs for toggle and switch
  src/components/switch/Switch.stories.mdx
  src/components/toggle/Toggle.stories.mdx
Labels: documentation

#305 Reorganize packages
  README.md
  package-lock.json
  package.json
  src/components/text/Text.stories.mdx
  src/index.tsx
Labels: bug, documentation

#306 Fix svgr error
  package.json
  src/components/button/Button.tsx
Labels: bug

#307 Update build settings
  .github/workflows/ release.yaml
  package.json
Labels: bug, enhancement

#308 Fix dependency errors
  package-lock.json
  package.json
Labels: bug

#310 [Docs] Add docs for PageTitle and Radio
  src/components/pagetitle/PageTitle.stories.mdx
  src/components/radiobutton/Radiobutton.stories.mdx
Labels: documentation

#304 [Docs] Add docs for modal and tabs
  src/components/modal/Modal.stories.mdx
  src/components/tabs/Tabs.stories.mdx
Labels: documentation

#309 [Docs] Add docs for sidebar
  src/components/sidebar/Sidebar.stories.mdx
Labels: documentation

#311 [Docs] Add docs to popover and table
  src/components/popover/Popover.stories.mdx
  src/components/table/Table.stories.mdx
Labels: documentation

#312 [Docs] Add docs for pie chart
  src/components/piechart/PieChart.stories.mdx
Labels: documentation

#313 [Docs] Add docs for navigation, spinner and textarea
  src/components/navigation/Navigation.stories.mdx
  src/components/spinner/Spinner.stories.mdx
  src/components/textarea/Textarea.stories.mdx
Labels: documentation

#319 [Docs] Add docs for input
  src/components/input/Input.stories.mdx
Labels: documentation

#320 Add missing type
  src/components/modal/Modal.tsx
  src/components/modal/ModalConfirm.tsx
Labels: bug

#321 Reserved instance icon
  package.json
  src/components/svgicon/SVGIcon.stories.mdx
  src/utils/icons/cloud-provider.tsx
Labels: enhancement
