Repository nordcloud/GNUI, pull requests merged in 2021-07, with the labels that each got.

#332 Refactor tooltip
  src/components/tooltip/Tooltip.tsx
  src/components/tooltip/hooks.ts
  src/components/tooltip/index.tsx
  src/components/tooltip/styles.ts
Labels: bug, enhancement

#339 [Bugfix] Add missing bracket
  src/components/tooltip/styles.ts
Labels: bug

#345 Update docs
  README.md
  amplify.yml
Labels: documentation
