Repository nordcloud/GNUI, pull requests merged in 2021-11, with the labels that each got.

#384 Fix Theme switcher
  package-lock.json
  package.json
  src/theme/switcher.ts
Labels: bug

#387 Flatten tabs children
  package-lock.json
  package.json
  src/components/tabs/Tabs.tsx
  src/utils/flattenChildren/flattenChildren.spec.tsx
  src/utils/flattenChildren/flattenChildren.ts
  src/utils/flattenChildren/index.ts
Labels: enhancement

#388 Add Nordcloud eslint config
  .eslintrc.js
  .prettierrc
  .stylelintrc
  package-lock.json
  package.json
  prettier.config.js
  src/components/extendedPagination/ExtendedPagination.spec.tsx
  src/components/modal/Modal.tsx
  src/components/modal/ModalConfirm.tsx
  src/components/multiselect/Multiselect.tsx
  src/components/sidebar/Sidebar.tsx
  src/components/spinner/Spinner.tsx
  src/components/tabs/Tabs.tsx
  stylelint.config.js
  tsconfig.json
  yarn.lock
Labels: style, dependencies

#391 Update eslint config
  .eslintrc.js
  package-lock.json
  package.json
  yarn.lock
Labels: dependencies
