Repository nordcloud/GNUI, pull requests merged in 2022-04, with the labels that each got.

#449 [KLAR-4512] create new tabs styling
  package.json
  src/components/tabs/Tabs.tsx
Labels: style

#450 Update packages
  .storybook/main.js
  .storybook/preview.js
  DOCS_GUIDE.md
  package-lock.json
  package.json
  src/components/accordion/Accordion.stories.mdx
  src/components/barchart/BarChart.stories.mdx
  src/components/box/Box.stories.mdx
  src/components/breadcrumbs/Breadcrumbs.stories.mdx
  src/components/button/Button.stories.mdx
  src/components/checkbox/Checkbox.stories.mdx
  src/components/checkboxTree/CheckboxTree.stories.mdx
  src/components/datepicker/Datepicker.stories.mdx
  src/components/dropdown/Dropdown.stories.mdx
  src/components/extendedPagination/ExtendedPagination.stories.mdx
  src/components/extendedPopover/ExtendedPopover.stories.mdx
  src/components/extendedTooltip/ExtendedTooltip.stories.mdx
  src/components/form/Form.stories.mdx
  src/components/heading/Headings.stories.mdx
  src/components/input/Input.stories.mdx
  src/components/list/List.stories.mdx
  src/components/loader/Loader.stories.mdx
  src/components/message/Message.stories.mdx
  src/components/modal/Modal.stories.mdx
  src/components/navigation/Navigation.stories.mdx
  src/components/navigationBar/NavigationBar.stories.mdx
  src/components/pagetitle/PageTitle.stories.mdx
  src/components/pagination/Pagination.stories.mdx
  src/components/piechart/PieChart.stories.mdx
  src/components/popover/Popover.stories.mdx
  src/components/radiobutton/Radiobutton.stories.mdx
  src/components/select/Select.stories.mdx
  src/components/selectbutton/SelectButton.stories.mdx
  src/components/sidebar/Sidebar.stories.mdx
  src/components/spacer/Spacer.stories.mdx
  src/components/spinner/Spinner.stories.mdx
  src/components/stickybar/StickyBar.stories.mdx
  src/components/svgicon/SVGIcon.stories.mdx
  src/components/switch/Switch.stories.mdx
  src/components/table/Table.stories.mdx
  src/components/tabs/Tabs.stories.mdx
  src/components/tag/Tag.stories.mdx
  src/components/text/Text.stories.mdx
  src/components/textarea/Textarea.stories.mdx
  src/components/toggle/Toggle.stories.mdx
  src/components/tooltip/Tooltip.stories.mdx
  src/stories/Applications.stories.mdx
  src/stories/Dashboard.stories.mdx
  src/stories/GnuiColors.stories.mdx
  src/stories/Grid.stories.mdx
  src/stories/TotalSpend.stories.mdx
  src/stories/Wizard.stories.mdx
  src/stories/appDetails.stories.mdx
  src/stories/ouDetails.stories.mdx
  yarn.lock
Labels: style, dependencies

#456 Fix tabs border styling
  package.json
  src/components/tabs/Tabs.tsx
Labels: bug

#459 Patch react-awesome-styled-grid
  package-lock.json
  package.json
  patches/react-awesome-styled-grid+3.1.4.patch
Labels: bug
