Repository nordcloud/GNUI, pull requests merged in 2023-02, with the labels that each got.

#559 Pin node versions
  package-lock.json
  package.json
Labels: dependencies

#562 Fix stacking of elements
  package-lock.json
  package.json
  src/components/loader/Loader.tsx
  src/components/modal/Modal.tsx
  src/components/modal/ModalConfirm.tsx
  src/components/modal/styles.ts
  src/components/modal/types.ts
  src/components/sidebar/Sidebar.tsx
  src/components/sidebar/styles.tsx
  src/components/sidebar/types.ts
  src/utils/browserCompatibility.ts
Labels: style

#564 Setting up `max-width` to modal
  src/components/modal/Modal.stories.mdx
  src/components/modal/styles.ts
Labels: bug
